# Purpose: cross-language diagnostics/LOO/sensitivity on the same analytic draws.
# Inputs: directory generated by analytic-workflow.py; separate output directory.
# Assumptions: iid Normal response, known SD=1, independent exact posterior draws.
# Expected output: R summaries/pointwise scores/plots and sensitivity records.
# Interpretation: API/shape parity test, not independent validation of real MCMC.
# Failure modes: axis mismatch, likelihood/transform errors, missing packages.
# Next action: compare results to Python/exact LOO; adapt a real fit with all gates.
# Source: E02/E04/E06/E07; M-LOO/M-SENSE; translated analytic example.
args <- commandArgs(trailingOnly = TRUE)
stopifnot(length(args) == 2)
dir.create(args[2], recursive = TRUE, showWarnings = FALSE)
library(posterior)
library(loo)
set.seed(71)
dat <- read.csv(file.path(args[1], "data.csv"))
results <- list()
records <- list()
for (name in c("base", "strong")) {
  df <- read.csv(file.path(args[1], paste0(name, "-draws.csv")))
  chains <- length(unique(df$chain)); iterations <- nrow(df) / chains
  stopifnot(all(df$chain == rep(0:(chains-1), each = iterations)))
  mu <- array(df$mu, dim = c(iterations, chains))
  draws <- as_draws_array(array(mu, dim = c(iterations, chains, 1),
                               dimnames = list(NULL, NULL, "mu")))
  summary <- summarise_draws(draws, "mean", "sd", "rhat", "ess_bulk", "ess_tail", "mcse_mean",
                            mcse_q95 = function(x) mcse_quantile(x, probs = .95))
  write.csv(summary, file.path(args[2], paste0(name, "-summary.csv")), row.names = FALSE)
  ll_matrix <- vapply(dat$y, function(y) dnorm(y, as.vector(mu), 1, log = TRUE), numeric(length(mu)))
  ll <- array(ll_matrix, dim = c(iterations, chains, nrow(dat)))
  # Independent analytic draws justify r_eff=1 for score parity; real MCMC uses relative_eff.
  results[[name]] <- loo(ll, r_eff = 1, save_psis = TRUE)
  write.csv(data.frame(obs_id = dat$obs_id,
                      elpd_i = results[[name]]$pointwise[, "elpd_loo"],
                      pareto_k = pareto_k_values(results[[name]])),
            file.path(args[2], paste0(name, "-loo.csv")), row.names = FALSE)
  sd_prior <- if (name == "base") 2 else .2
  lp <- array(dnorm(as.vector(mu), 0, sd_prior, log = TRUE), dim = c(iterations, chains, 1),
              dimnames = list(NULL, NULL, "lprior"))
  ll_names <- ll; dimnames(ll_names) <- list(NULL, NULL, paste0("log_lik[", seq_len(nrow(dat)), "]"))
  if (requireNamespace("priorsense", quietly = TRUE)) {
    psdata <- priorsense::create_priorsense_data(draws,
                 log_prior = as_draws_array(lp), log_lik = as_draws_array(ll_names))
    sensitivity <- priorsense::powerscale_sensitivity(psdata, variable = "mu", moment_match = FALSE)
    capture.output(print(sensitivity), file = file.path(args[2], paste0(name, "-sensitivity.txt")))
    sequence <- priorsense::powerscale_sequence(psdata, variable = "mu", lower_alpha = .8,
                                                upper_alpha = 1.25, length = 3, moment_match = FALSE)
    p <- priorsense::powerscale_plot_quantities(sequence)
    ggplot2::ggsave(file.path(args[2], paste0(name, "-sensitivity.png")), plot = p, width = 7, height = 4)
  }
  for (component in c("prior", "likelihood")) {
    lc <- if (component == "prior") as.vector(lp) else rowSums(ll_matrix)
    for (alpha in c(.8,.99,1.01,1.25)) {
      ps <- psis(matrix((alpha-1)*lc,ncol=1), r_eff=1)
      w <- as.vector(weights(ps, normalize=TRUE, log=FALSE))
      records[[length(records)+1]] <- data.frame(model=name, component=component, alpha=alpha,
                                                pareto_k=pareto_k_values(ps), weight_ess=1/sum(w^2))
    }
  }
  if (requireNamespace("bayesplot", quietly = TRUE)) {
    ggplot2::ggsave(file.path(args[2], paste0(name,"-rank.png")),
                   bayesplot::mcmc_rank_overlay(draws), width=7, height=4)
    yrep <- matrix(rnorm(300*nrow(dat), rep(as.vector(mu)[1:300],each=nrow(dat)),1),
                   nrow=300,byrow=TRUE)
    ggplot2::ggsave(file.path(args[2],paste0(name,"-ppc.png")),
                   bayesplot::ppc_stat(dat$y,yrep,stat="sd"),width=7,height=4)
  }
}
comparison <- loo_compare(results)
write.csv(comparison, file.path(args[2],"comparison.csv"))
write.csv(loo_model_weights(results,method="stacking"),file.path(args[2],"stacking.csv"))
write.csv(do.call(rbind,records),file.path(args[2],"power-weights.csv"),row.names=FALSE)
print(comparison,simplify=FALSE)
